/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOTravelling;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdallah Ali
 */
public class OOTravels extends javax.swing.JFrame {
    
    
    
    public OOTravels () {
        initComponents();
        
        
    }
    
    double Gross;
    cFlight cost = new cFlight();

    /**
     * Creates new form OOTravels
     */
    //public OOTravels() {
    //    initComponents();
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jrbReturn = new javax.swing.JRadioButton();
        jrbStandard = new javax.swing.JRadioButton();
        jrbEconomy = new javax.swing.JRadioButton();
        jrbFirstClass = new javax.swing.JRadioButton();
        jrbSingle = new javax.swing.JRadioButton();
        jchkSpecialNeeds = new javax.swing.JCheckBox();
        jlblStandard = new javax.swing.JLabel();
        jlblEconomy = new javax.swing.JLabel();
        jlblFirstClass = new javax.swing.JLabel();
        jlblSingle = new javax.swing.JLabel();
        jlblReturn = new javax.swing.JLabel();
        jbtnHistory = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtLastname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtPostCode = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtTelephone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtNationality = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jchkAirportTax = new javax.swing.JCheckBox();
        jchkInsurance = new javax.swing.JCheckBox();
        jchkAirMiles = new javax.swing.JCheckBox();
        jchkExtLuagge = new javax.swing.JCheckBox();
        jcmbTPackages = new javax.swing.JComboBox<>();
        jcmbDeparture = new javax.swing.JComboBox<>();
        jcmbDestination = new javax.swing.JComboBox<>();
        jcmbAType = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jcmbATime = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubtotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbtnReceipt = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel1.setText("Travel Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1413, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 1580, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbReturn.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jrbReturn.setText("Return");
        jrbReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbReturnActionPerformed(evt);
            }
        });
        jPanel2.add(jrbReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jrbStandard.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jrbStandard.setText("Standard");
        jrbStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbStandardActionPerformed(evt);
            }
        });
        jPanel2.add(jrbStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jrbEconomy.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jrbEconomy.setText("Economy");
        jrbEconomy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEconomyActionPerformed(evt);
            }
        });
        jPanel2.add(jrbEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jrbFirstClass.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jrbFirstClass.setText("First Class");
        jrbFirstClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFirstClassActionPerformed(evt);
            }
        });
        jPanel2.add(jrbFirstClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jrbSingle.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jrbSingle.setText("Single");
        jPanel2.add(jrbSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jchkSpecialNeeds.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jchkSpecialNeeds.setText("Special Needs");
        jPanel2.add(jchkSpecialNeeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jlblStandard.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblStandard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblStandard.setText("0");
        jlblStandard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jlblStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 130, 40));

        jlblEconomy.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblEconomy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblEconomy.setText("0");
        jlblEconomy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jlblEconomy, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 130, 40));

        jlblFirstClass.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblFirstClass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblFirstClass.setText("0");
        jlblFirstClass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jlblFirstClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 130, 40));

        jlblSingle.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblSingle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSingle.setText("0");
        jlblSingle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jlblSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, 40));

        jlblReturn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblReturn.setText("0");
        jlblReturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.add(jlblReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 130, 40));

        jbtnHistory.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jbtnHistory.setText("History");
        jbtnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHistoryActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        jbtnSave.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 710, 270));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel2.setText("First name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 40));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 280, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel9.setText("Last name");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, 40));

        jtxtLastname.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel3.add(jtxtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 280, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel10.setText("Address");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 40));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel3.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 280, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel11.setText("Post Code");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 40));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel3.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 280, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel12.setText("Telephone");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 40));

        jtxtTelephone.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel3.add(jtxtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 280, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel13.setText("Email");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 40));

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 280, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel14.setText("Nationality");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 190, 40));

        jtxtNationality.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jPanel3.add(jtxtNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 280, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 550, 390));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel18.setText("Departure");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel19.setText("Destination");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setText("Accommodation Type");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 230, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel21.setText("Travel Packages");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 40));

        jchkAirportTax.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jchkAirportTax.setText("Airport Tax");
        jchkAirportTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAirportTaxActionPerformed(evt);
            }
        });
        jPanel4.add(jchkAirportTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jchkInsurance.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jchkInsurance.setText("Travelling Insurance");
        jPanel4.add(jchkInsurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jchkAirMiles.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jchkAirMiles.setText("Air Miles Over 20000");
        jPanel4.add(jchkAirMiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jchkExtLuagge.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jchkExtLuagge.setText("Ext luggage");
        jPanel4.add(jchkExtLuagge, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jcmbTPackages.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jcmbTPackages.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Luxury Packages", "Adventure Packages", "Cultural Packages" }));
        jcmbTPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbTPackagesActionPerformed(evt);
            }
        });
        jPanel4.add(jcmbTPackages, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 340, 40));

        jcmbDeparture.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jcmbDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Cairo Airport", "Assuit Airport", "El Alamein Airport", "Taba Airport", "El minya Airport", "Siwa Airport", " " }));
        jPanel4.add(jcmbDeparture, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 340, 40));

        jcmbDestination.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jcmbDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Canada in Toronto", "Canada in Ottawa", "Norway in Oslo", "Nigeria in Lagos", "USA in DFW", "South Africa in Cape Town", "UK in London", "UK in Wales", "Ireland in Dublin", "Ghana in Accra", "Kenya in Nairobi", "France in Paris" }));
        jcmbDestination.setEnabled(false);
        jcmbDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDestinationActionPerformed(evt);
            }
        });
        jPanel4.add(jcmbDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 340, 40));

        jcmbAType.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jcmbAType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Hotel", "Hostel", "Resort" }));
        jcmbAType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbATypeActionPerformed(evt);
            }
        });
        jPanel4.add(jcmbAType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 340, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setText("Accommodation Time");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, 40));

        jcmbATime.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jcmbATime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "4-Days", "5-Days", "7-Days", "11-Days", "13-Days", "15-Days", "20-Days", "25-Days" }));
        jPanel4.add(jcmbATime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 340, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 600, 390));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 390, 530));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel25.setText("Receipt");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 130, 410, 590));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel15.setText("Tax");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel16.setText("Subtotal");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel17.setText("Total");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 40));

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.add(jlblTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 130, 40));

        jlblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.add(jlblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 130, 40));

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 130, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 440, 190));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jbtnPrint.setText("Print");

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(jbtnReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 722, 860, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstnameActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jchkAirportTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAirportTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchkAirportTaxActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        cQuit cExit = new cQuit();
        cExit.quit();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        
        
        cCostTax iTax = new cCostTax();
        double iTaxes, subtotal, total;
        
        if (jrbReturn.isSelected())
        {
            subtotal = Gross * 2 ;
            String isubtotal =String.format("$%.2f", subtotal);
            jlblSubtotal.setText(isubtotal);
            iTaxes = iTax.cFindTax(subtotal);
            String Tax =String.format("$%.2f", iTaxes);
            jlblTax.setText(Tax);
            String iTotal =String.format("$%.2f", subtotal + iTaxes);
            jlblTotal.setText(iTotal);
            
            jlblReturn.setText(isubtotal);
        }
        else
        {
            subtotal = Gross;
            String isubtotal =String.format("$%.2f", subtotal);
            jlblSubtotal.setText(isubtotal);
            iTaxes = iTax.cFindTax(subtotal);
            String Tax =String.format("$%.2f", iTaxes);
            jlblTax.setText(Tax);
            String iTotal =String.format("$%.2f", subtotal + iTaxes);
            jlblTotal.setText(iTotal);
        }
        
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jcmbDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDestinationActionPerformed
        // Canada - 7 Days in Toronto
        
        if ((jcmbDestination.getSelectedItem().equals("Canada in Toronto")) && jrbStandard.isSelected())
        {
            Gross = cost.Canada_T ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Canada in Ottawa")) && jrbStandard.isSelected())
        {
            Gross = cost.Canada_O ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Norway in Oslo")) && jrbStandard.isSelected())
        {
            Gross = cost.Norway ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Nigeria in Lagos")) && jrbStandard.isSelected())
        {
            Gross = cost.Nieria ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("USA in DFW")) && jrbStandard.isSelected())
        {
            Gross = cost.USA_D ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("South Africa in Cape Town")) && jrbStandard.isSelected())
        {
            Gross = cost.SAfrica ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("UK in London")) && jrbStandard.isSelected())
        {
            Gross = cost.UK_L ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("UK in Wales")) && jrbStandard.isSelected())
        {
            Gross = cost.UK_W ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Ireland in Dublin")) && jrbStandard.isSelected())
        {
            Gross = cost.Ireland ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Ghana in Accra")) && jrbStandard.isSelected())
        {
            Gross = cost.Ghana ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Kenya in Nairobi")) && jrbStandard.isSelected())
        {
            Gross = cost.Kenya ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("France in Paris")) && jrbStandard.isSelected())
        {
            Gross = cost.France ;
            String Cost =String.format("$%.2f", Gross);
            jlblStandard.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        //==================================================================================================================================
        
        if ((jcmbDestination.getSelectedItem().equals("Canada in Toronto")) && jrbEconomy.isSelected())
        {
            Gross = cost.Canada_T + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Canada in Ottawa")) && jrbEconomy.isSelected())
        {
            Gross = cost.Canada_O + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Norway in Oslo")) && jrbEconomy.isSelected())
        {
            Gross = cost.Norway + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Nigeria in Lagos")) && jrbEconomy.isSelected())
        {
            Gross = cost.Nieria + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("USA in DFW")) && jrbEconomy.isSelected())
        {
            Gross = cost.USA_D + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("South Africa in Cape Town")) && jrbEconomy.isSelected())
        {
            Gross = cost.SAfrica + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("UK in London")) && jrbEconomy.isSelected())
        {
            Gross = cost.UK_L + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("UK in Wales")) && jrbEconomy.isSelected())
        {
            Gross = cost.UK_W + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Ireland in Dublin")) && jrbEconomy.isSelected())
        {
            Gross = cost.Ireland + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Ghana in Accra")) && jrbEconomy.isSelected())
        {
            Gross = cost.Ghana + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Kenya in Nairobi")) && jrbEconomy.isSelected())
        {
            Gross = cost.Kenya + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        if ((jcmbDestination.getSelectedItem().equals("France in Paris")) && jrbEconomy.isSelected())
        {
            Gross = cost.France + 50 ;
            String Cost =String.format("$%.2f", Gross );
            jlblEconomy.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        //==================================================================================================================================
        
        if ((jcmbDestination.getSelectedItem().equals("Canada in Toronto")) && jrbFirstClass.isSelected())
        {
            Gross = cost.Canada_T + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Canada in Ottawa")) && jrbFirstClass.isSelected())
        {
            Gross = cost.Canada_O + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Norway in Oslo")) && jrbFirstClass.isSelected())
        {
            Gross = cost.Norway + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Nigeria in Lagos")) && jrbFirstClass.isSelected())
        {
            Gross = cost.Nieria + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("USA in DFW")) && jrbFirstClass.isSelected())
        {
            Gross = cost.USA_D + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("South Africa in Cape Town")) && jrbFirstClass.isSelected())
        {
            Gross = cost.SAfrica + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("UK in London")) && jrbFirstClass.isSelected())
        {
            Gross = cost.UK_L + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("UK in Wales")) && jrbFirstClass.isSelected())
        {
            Gross = cost.UK_W + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Ireland in Dublin")) && jrbFirstClass.isSelected())
        {
            Gross = cost.Ireland + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Ghana in Accra")) && jrbFirstClass.isSelected())
        {
            Gross = cost.Ghana + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        if ((jcmbDestination.getSelectedItem().equals("Kenya in Nairobi")) && jrbFirstClass.isSelected())
        {
            Gross = cost.Kenya + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
        
        if ((jcmbDestination.getSelectedItem().equals("France in Paris")) && jrbFirstClass.isSelected())
        {
            Gross = cost.France + 140 ;
            String Cost =String.format("$%.2f", Gross );
            jlblFirstClass.setText(Cost);
            jlblSingle.setText(Cost);
            jrbSingle.setSelected(true);
        }
    }//GEN-LAST:event_jcmbDestinationActionPerformed

    private void jrbStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbStandardActionPerformed
        // TODO add your handling code here:
        
        if (jrbStandard.isSelected()== true)
        {
            jcmbDestination.setEnabled(true);
            jcmbDestination.setSelectedItem("None");
            jrbEconomy.setSelected(false);
            jrbFirstClass.setSelected(false);
            jlblEconomy.setText("0");
            jlblFirstClass.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
        }
        if (jrbStandard.isSelected()== false)
        {
            jcmbDestination.setSelectedItem("None");
            jcmbDestination.setEnabled(false);
            jlblStandard.setText("0");
        }
    }//GEN-LAST:event_jrbStandardActionPerformed

    private void jrbEconomyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEconomyActionPerformed
        
        if (jrbEconomy.isSelected()== true)
        {
            jcmbDestination.setEnabled(true);
            jcmbDestination.setSelectedItem("None");
            jrbStandard.setSelected(false);
            jrbFirstClass.setSelected(false);
            jlblStandard.setText("0");
            jlblFirstClass.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
        }
        if (jrbEconomy.isSelected()== false)
        {
            jcmbDestination.setSelectedItem("None");
            jcmbDestination.setEnabled(false);
            jlblEconomy.setText("0");
        }
        
    }//GEN-LAST:event_jrbEconomyActionPerformed

    private void jrbFirstClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFirstClassActionPerformed
        
        if (jrbFirstClass.isSelected()== true)
        {
            jcmbDestination.setEnabled(true);
            jcmbDestination.setSelectedItem("None");
            jrbStandard.setSelected(false);
            jrbEconomy.setSelected(false);
            jlblStandard.setText("0");
            jlblEconomy.setText("0");
            jlblSingle.setText("0");
            jlblReturn.setText("0");
        }
        if (jrbFirstClass.isSelected()== false)
        {
            jcmbDestination.setSelectedItem("None");
            jcmbDestination.setEnabled(false);
            jlblFirstClass.setText("0");
        }
    }//GEN-LAST:event_jrbFirstClassActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtFirstname.setText(null);
        jlblTax.setText(null);
        jlblSubtotal.setText(null);
        jlblTotal.setText(null);
        jtxtLastname.setText(null);
        jtxtPostCode.setText(null);
        jtxtAddress.setText(null);
        jtxtTelephone.setText(null);
        jtxtEmail.setText(null);
        jtxtNationality.setText(null);
        jtxtFirstname.setText(null);
        jtxtPostCode.setText(null);
        jtxtReceipt.setText(null);
        jlblStandard.setText("0");
        jlblEconomy.setText("0");
        jlblFirstClass.setText("0");
        jlblSingle.setText("0");
        jlblReturn.setText("0");
        jcmbDeparture.setSelectedItem("None");
        jcmbTPackages.setSelectedItem("None");
        jcmbAType.setSelectedItem("None");
        jcmbDestination.setSelectedItem("None");
        jrbStandard.setSelected(false);
        jrbEconomy.setSelected(false);
        jrbFirstClass.setSelected(false);
        jrbSingle.setSelected(false);
        jrbReturn.setSelected(false);
        jchkAirportTax.setSelected(false);
        jchkSpecialNeeds.setSelected(false);
        jchkInsurance.setSelected(false);
        jchkAirMiles.setSelected(false);
        jchkExtLuagge.setSelected(false);
        jrbStandard.setSelected(false);
        jrbEconomy.setSelected(false);
        jrbFirstClass.setSelected(false);
        jrbSingle.setSelected(false);
        jrbReturn.setSelected(false);
        
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jrbReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbReturnActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
        
        
    // الحصول على التاريخ والوقت الحالي
    Calendar timer = Calendar.getInstance();
    timer.getTime();
    SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
    String iTime = (tTime.format(timer.getTime()));

    SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
    String iDate = (Tdate.format(timer.getTime()));

    // إنشاء مرجع عشوائي
    int num1;
    String ref = "";
    num1 = 1325 + (int) (Math.random() * 4238);
    ref += num1 + 1325;

    // جلب الحزمة المختارة
    String selectedPackage = jcmbTPackages.getSelectedItem().toString();
    String packageDetails = "No package selected";

    // إذا تم اختيار حزمة، احصل على التفاصيل من Factory
    if (!selectedPackage.equals("None")) {
        TravelPackage travelPackage = TravelPackageFactory.createPackage(selectedPackage.replace(" Packages", ""));
        if (travelPackage != null) {
            packageDetails = travelPackage.getDescription();
        }
    }

    // جلب نوع الإقامة المختار
    String selectedAccommodation = jcmbAType.getSelectedItem().toString();
    String accommodationDetails = "No accommodation selected";

    // إذا تم اختيار نوع إقامة، احصل على التفاصيل من Factory
    if (!selectedAccommodation.equals("None")) {
        Accommodation accommodation = AccommodationFactory.createAccommodation(selectedAccommodation);
        if (accommodation != null) {
            accommodationDetails = accommodation.getDetails();
        }
    }

    // جمع البيانات من المستخدم
    String Firstname = jtxtFirstname.getText();
    String Lastname = jtxtLastname.getText();
    String address = jtxtAddress.getText();
    String postcode = jtxtPostCode.getText();
    String telephone = jtxtTelephone.getText();
    String Email = jtxtEmail.getText();
    String rTax = jlblTax.getText();
    String rSubTotal = jlblSubtotal.getText();
    String rTotal = jlblTotal.getText();

    // استخدام Singleton للحصول على كائن BookingManager
    BookingManager bookingManager = BookingManager.getInstance();

    // تحديد نوع الحجز بناءً على الاختيارات (Standard, Economy, FirstClass)
    String bookingType = "";
    if (jrbStandard.isSelected()) {
        bookingType = "Standard";
    } else if (jrbEconomy.isSelected()) {
        bookingType = "Economy";
    } else if (jrbFirstClass.isSelected()) {
        bookingType = "FirstClass";
    } else {
        JOptionPane.showMessageDialog(this, "Please select a booking type!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // إذا لم يتم اختيار أي نوع، إظهار رسالة خطأ
    }

    // تفاصيل الحجز: يمكن تضمين التفاصيل مثل الوجهة، المجموعات الخاصة أو أي شيء آخر
    String bookingDetails = "Destination: " + jcmbDestination.getSelectedItem() + 
                            ", Name: " + Firstname + " " + Lastname + 
                            ", Address: " + address + ", Email: " + Email + 
                            ", Total Cost: " + rTotal;

    // إضافة الحجز إلى النظام باستخدام الـ Singleton
    bookingManager.addBooking(bookingType, bookingDetails);

    // استرجاع الإجمالي النهائي من الحقل النصي الخاص بـ Total
    if (rTotal.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Total cost is missing!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // إذا كان الحقل فارغًا، إظهار رسالة خطأ
    }

    // استخدام UserProfileManager لتحديث سجل الحجز ونقاط الولاء
    UserProfileManager userProfile = UserProfileManager.getInstance();

    // إعداد تفاصيل الحجز
    String userBookingDetails = "Booking Type: " + bookingType + ", Cost: " + rTotal;
    userProfile.addBookingToHistory(userBookingDetails);

    // زيادة نقاط الولاء بناءً على تكلفة الحجز
    try {
        int pointsEarned = (int) Double.parseDouble(rTotal.replace("$", "")); // إزالة علامة الدولار وتحويل الإجمالي إلى رقم
        userProfile.addLoyaltyPoints(pointsEarned);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid total cost format!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // إذا كان التنسيق غير صالح
    }

    // طباعة تفاصيل المستخدم في الإيصال
    jtxtReceipt.append("User: " + userProfile.getUsername() + "\n");
    jtxtReceipt.append("Booking Type: " + bookingType + "\n");
    jtxtReceipt.append("Loyalty Points: " + userProfile.getLoyaltyPoints() + "\n");

    // طباعة الإيصال
    jtxtReceipt.append("\tTravel Management System:\n\n"
        + "Ref:\t\t\t" + ref
        + "\n---------------------------------------------"
        + "\nFirstname:\t\t" + Firstname
        + "\nLastname:\t\t" + Lastname
        + "\nAddress:\t\t" + address
        + "\nPostcode:\t\t" + postcode
        + "\nTelephone:\t\t" + telephone
        + "\nEmail:\t\t\t" + Email       
        + "\nTax:\t\t\t" + rTax
        + "\nSub Total:\t\t" + rSubTotal
        + "\nTotal:\t\t\t" + rTotal
        + "\n---------------------------------------------"
        + "\nDate:" + iDate + " \tTime:" + iTime
        + "\n\n\tThanks for Using \n\tTravel Management System"
        + "\n\n\tEdit By \n\tEng/ Abdallah Ali"        
    );

    // تعديل طباعة الإيصال لإضافة الحزمة
    jtxtReceipt.append("\nTravel Package:\t" + packageDetails + "\n");

    // تعديل طباعة الإيصال لإضافة نوع الإقامة
    jtxtReceipt.append("Accommodation Type:\t" + accommodationDetails + "\n");
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jcmbTPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbTPackagesActionPerformed
        // TODO add your handling code here:
        String selectedPackage = jcmbTPackages.getSelectedItem().toString();

        // إذا كان الاختيار هو None، لا تفعل شيئًا
        if (selectedPackage.equals("None")) {
            JOptionPane.showMessageDialog(this, "Please select a valid package.");
            return;
        }

        // استخدام Factory لإنشاء الحزمة وعرض التفاصيل
        TravelPackage travelPackage = TravelPackageFactory.createPackage(selectedPackage.replace(" Packages", ""));
        if (travelPackage != null) {
            JOptionPane.showMessageDialog(this, "Selected Package: " + travelPackage.getDescription());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid package selected.");
        }
       
    }//GEN-LAST:event_jcmbTPackagesActionPerformed

    private void jcmbATypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbATypeActionPerformed
        // TODO add your handling code here:
        
            String selectedAccommodation = jcmbAType.getSelectedItem().toString();

        if (selectedAccommodation.equals("None")) {
            JOptionPane.showMessageDialog(this, "Please select a valid accommodation type.");
            return;
        }

        Accommodation accommodation = AccommodationFactory.createAccommodation(selectedAccommodation);
        if (accommodation != null) {
            JOptionPane.showMessageDialog(this, "Selected Accommodation: " + accommodation.getDetails());
        } else {
            JOptionPane.showMessageDialog(this, "Invalid accommodation type selected.");
        }
        
    }//GEN-LAST:event_jcmbATypeActionPerformed

    private void jbtnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHistoryActionPerformed
        // TODO add your handling code here:
            UserProfileManager userProfile = UserProfileManager.getInstance();
            List<String> history = userProfile.getBookingHistory();

            if (history.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No bookings found for user: " + userProfile.getUsername());
            } else {
                StringBuilder historyDetails = new StringBuilder("Booking History:\n");
                for (String booking : history) {
                    historyDetails.append(booking).append("\n");
                }
                JOptionPane.showMessageDialog(this, historyDetails.toString());
            }
    }//GEN-LAST:event_jbtnHistoryActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        String username = jtxtFirstname.getText() + " " + jtxtLastname.getText();

        // حفظ تفاصيل المستخدم
        UserProfileManager userProfile = UserProfileManager.getInstance();
        userProfile.setUserDetails(username);

        JOptionPane.showMessageDialog(this, "User details saved for: " + userProfile.getUsername());
        
    }//GEN-LAST:event_jbtnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OOTravels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OOTravels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnHistory;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JCheckBox jchkAirMiles;
    private javax.swing.JCheckBox jchkAirportTax;
    private javax.swing.JCheckBox jchkExtLuagge;
    private javax.swing.JCheckBox jchkInsurance;
    private javax.swing.JCheckBox jchkSpecialNeeds;
    private javax.swing.JComboBox<String> jcmbATime;
    private javax.swing.JComboBox<String> jcmbAType;
    private javax.swing.JComboBox<String> jcmbDeparture;
    private javax.swing.JComboBox<String> jcmbDestination;
    private javax.swing.JComboBox<String> jcmbTPackages;
    private javax.swing.JLabel jlblEconomy;
    private javax.swing.JLabel jlblFirstClass;
    private javax.swing.JLabel jlblReturn;
    private javax.swing.JLabel jlblSingle;
    private javax.swing.JLabel jlblStandard;
    private javax.swing.JLabel jlblSubtotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JRadioButton jrbEconomy;
    private javax.swing.JRadioButton jrbFirstClass;
    private javax.swing.JRadioButton jrbReturn;
    private javax.swing.JRadioButton jrbSingle;
    private javax.swing.JRadioButton jrbStandard;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtNationality;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtTelephone;
    // End of variables declaration//GEN-END:variables
}
